env:
 global:
  - CABALVER=1.20
 matrix:
  - GHCVER=7.0.4
  - GHCVER=7.2.2
  - GHCVER=7.4.2
  - GHCVER=7.6.3
  - GHCVER=7.8.3
  - GHCVER=head

matrix:
 allow_failures:
  - env: GHCVER=head

before_install:
 - sudo add-apt-repository -y ppa:hvr/ghc
 - sudo apt-get update -qq
 - sudo apt-get install -qq cabal-install-$CABALVER ghc-$GHCVER libopenal-dev libalut-dev
 - export PATH="/opt/ghc/$GHCVER/bin:$PATH"

install:
 - cabal-$CABALVER update
 - ghc --version
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
 - cd OpenGLRaw
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/GLURaw.git
 - cd GLURaw
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGL.git
 - cd OpenGL
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list
 - pushd ..
 - git clone --depth=100 --quiet https://github.com/haskell-openal/OpenAL.git
 - cd OpenAL
 - cabal-$CABALVER install --enable-documentation
 - popd
 - ghc-pkg list

script:
 - cabal-$CABALVER install --enable-documentation
 - cabal-$CABALVER sdist
 - ghc-pkg list
 - pushd examples/Basic
 - ghc --make -Wall -O2 HelloWorld.hs
 - ghc --make -Wall -O2 OpenALInfo.hs
 - ghc --make -Wall -O2 PlayFile.hs
 - popd
 - pushd examples/TestSuite
 - ghc --make -Wall -O2 TestErrorStuff.hs
 - ghc --make -Wall -O2 TestFileLoader.hs
 - ghc --make -Wall -O2 TestMemoryLoader.hs
 - ghc --make -Wall -O2 TestVersion.hs
 - ghc --make -Wall -O2 TestWaveforms.hs
 - popd
