language: haskell
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq haskell-platform-doc libopenal-dev libalut-dev
  - ghc-pkg list
  - pushd ..
  - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGLRaw.git
  - cd OpenGLRaw
  - git checkout
  - cabal install --enable-documentation
  - popd
  - ghc-pkg list
  - pushd ..
  - git clone --depth=100 --quiet https://github.com/haskell-opengl/GLURaw.git
  - cd GLURaw
  - git checkout
  - cabal install --enable-documentation
  - popd
  - ghc-pkg list
  - pushd ..
  - git clone --depth=100 --quiet https://github.com/haskell-opengl/OpenGL.git
  - cd OpenGL
  - git checkout
  - cabal install --enable-documentation
  - popd
  - ghc-pkg list
  - pushd ..
  - git clone --depth=100 --quiet https://github.com/haskell-openal/OpenAL.git
  - cd OpenAL
  - git checkout
  - cabal install --enable-documentation
  - popd
  - ghc-pkg list
script:
  - autoreconf
  - cabal install --enable-documentation
  - pushd examples/Basic
  - ghc --make -Wall -O2 HelloWorld.hs
  - ghc --make -Wall -O2 OpenALInfo.hs
  - ghc --make -Wall -O2 PlayFile.hs
  - popd
  - pushd examples/TestSuite
  - ghc --make -Wall -O2 TestErrorStuff.hs
  - ghc --make -Wall -O2 TestFileLoader.hs
  - ghc --make -Wall -O2 TestMemoryLoader.hs
  - ghc --make -Wall -O2 TestVersion.hs
  - ghc --make -Wall -O2 TestWaveforms.hs
  - popd
